<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\TavernController' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Controller\\TavernController.php';

return $this->services['App\Controller\TavernController'] = new \App\Controller\TavernController();
