<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4fBeSFL\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4fBeSFL/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4fBeSFL.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4fBeSFL\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container4fBeSFL\srcDevDebugProjectContainer(array(
    'container.build_hash' => '4fBeSFL',
    'container.build_id' => 'e4225460',
    'container.build_time' => 1518338592,
));
