<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxClfQx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxClfQx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFxClfQx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFxClfQx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFxClfQx\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'FxClfQx',
    'container.build_id' => '4d1ce84d',
    'container.build_time' => 1518284301,
));
